// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvpahnopmpwuifupezyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cGFobm9wbXB3dWlmdXBlenlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDUwMTAsImV4cCI6MjA2NjAyMTAxMH0.9VajE-axog41NPrGdJ4XPA0LJG7UOKyqs69COTn3Eew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);